name: Build Test & Drop artifacts

on:
  push:
    branches:
     - poc-codesample

  pull_request:
    branches:
     - poc-codesample

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-test-drop-artifacts:
    name: Build Test & Drop artifacts
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - windows-latest
    
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      ProjectPath: './TestAPI/TestAPI/TestAPI.csproj'
      Configuration: 'Release'
      Solution: './TestAPI/TestAPI.sln'
      ArtifactName: 'drop'
      ArtifactPath: 'publish'
      PathToTestCoverage: './DotnetTemplate.Tests/TestResults/coverage.info'
      AZURE_WEBAPP_NAME : 'saas-poc-app'
    
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET 3.1 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Nuget Restore
        run: dotnet restore

      - name: Build Solution
        run: |
          dotnet build ${{ env.Solution }} --configuration ${{ env.Configuration }} /p:ContinuousIntegrationBuild=true 

    # - name: Build db
    # run: |
    # dotnet build ${{ env.dbSolution }} --configuration ${{ env.Configuration }} 

      - name: Run .NET Publish
        run: |
          dotnet publish ${{ env.ProjectPath }} --configuration ${{ env.Configuration }} --output ${{ env.ArtifactPath }}
      #          dotnet publish "WebAppPath/WebAppProject.csproj" -r "linux-x64" -o "project-linux-build/src" --self-contained

      - name: Drop Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ArtifactName }}
          path: ${{ env.ArtifactPath }}
     
    
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          ==app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.ArtifactPath }}'

  deploy:
        name: SCP files to server
        needs: build-test-drop-artifacts
        runs-on: ubuntu-latest
        
        steps:
         - name: Drop Artifact
           uses: actions/download-artifact@v3
           with: 
               name: ${{ env.ArtifactName }}
               path: ${{ env.ArtifactPath }}
          
          
         - name: SCP files via ssh key
           uses: garygrossgarten/github-action-scp@release
           with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              local: ${{ env.ArtifactPath }}
              remote: 'C:\poc'
              
           
           

