name: Powershell

on:
  push:
    branches:
     - POC-sample

  pull_request:
    branches:
     - POC-sample

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 0'

jobs:
  Powershell:
    name: Build Test & Drop artifacts
    runs-on: windows-latest
    steps:
               
      - name: 'Powershell script'
        uses: Amadevus/pwsh-script@v2
        id: script
        with: 
          script: |
               Invoke-WebRequest 'https://winscp.net/download/WinSCP-5.21.8-Setup.exe' -OutFile .\winscp.exe
               sleep 10
               Start-Process -FilePath ".\winscp.exe" -ArgumentList "/S /v/qn"
               
               
              
         
           

