name: Powershell

on:
  push:
    branches:
     - POC-sample

  pull_request:
    branches:
     - POC-sample

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 0'

jobs:
  Powershell:
    name: Powershell script 
    runs-on: self-hosted
    steps:
               
     - name: Perform a test from the command-line
       shell: pwsh
       run: |
         Get-Location 

              
         
           

